[package]
name = "der_broken"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.40"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = "1.0.219"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
